{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "task-manager.fullname" . }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "task-manager.selectorLabels" . | nindent 6 }}
  policyTypes: ["Ingress","Egress"]
  ingress:
    - from:
        {{- range .Values.networkPolicy.ingressFrom }}
        - {{ toYaml . | nindent 10 }}
        {{- end }}
      ports:
        - port: {{ .Values.service.port }}
  egress:
    {{- range .Values.networkPolicy.egressRules }}
    - to:
        {{- if .to }}
        {{- toYaml .to | nindent 8 }}
        {{- end }}
      ports:
        {{- toYaml .ports | nindent 8 }}
    {{- end }}
{{- end }}
