{{- if and .Values.secret.create (not .Values.secret.existingSecret) .Values.secret.databaseUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-manager.secretName" . }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secret.databaseUrlKey }}: {{ .Values.secret.databaseUrl | b64enc | quote }}
{{- end }}
