{{- if and .Values.secret.create (not .Values.secret.existingSecret) (or .Values.secret.databaseUrl .Values.secret.redisUrl) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-manager.secretName" . }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.databaseUrl }}
  {{ .Values.secret.databaseUrlKey }}: {{ .Values.secret.databaseUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.redisUrl }}
  {{ .Values.secret.redisUrlKey }}: {{ .Values.secret.redisUrl | b64enc | quote }}
  {{- end }}
{{- end }}
