apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tg-bot
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/cyprus7/testtask.git
    targetRevision: main
    path: deploy/helm/tg-bot
  destination:
    server: https://kubernetes.default.svc
    namespace: botstage
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: ["CreateNamespace=true","ServerSideApply=true"]
  revisionHistoryLimit: 10
