image:
  repository: ghcr.io/cyprus7/testtask/tgbot
  tag: "a5809fada874c31d9178b605f51f4b343a53d9c3"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: task20251104.test.chernov.us
      paths:
        - path: /tg/webhook
          pathType: Prefix
  tls:
    - hosts: [task20251104.test.chernov.us]
      secretName: task-manager-tls
env:
  PUBLIC_URL: "https://task20251104.test.chernov.us"
  WEBHOOK_PATH: "/tg/webhook"
  # BOT_TOKEN will be sourced from a secret
